 <h1 id="logo"><a href="index.html">lakeside</a></h1>
  <div class="widget_box d-flex">
    <div class="weather_cast">
      <div class="preview d-flex">
        <ul class="d-flex"></ul>
      </div>
      <div class="swiper container">
        <ul class="swiper-wrapper"></ul>
      </div>
      <div class="swiper-button-prev">◀</div>
      <div class="swiper-button-next">▶</div>
      <div class="shortcut">
        <div
          class="reservation d-flex justify-content-center align-items-center gap-4"
        >
          <div class="calendar"><a href="book.html">예약하기</a></div>
          <i class="fa-solid fa-calendar-plus"></i>
        </div>
        <div class="faq d-flex justify-content-center align-items-center gap-4">
          <div class="phone"><a href="">문의하기</a></div>
          <i class="fa-solid fa-square-phone-flip"></i>
        </div>
        <div
          class="location d-flex justify-content-center align-items-center gap-4"
        >
          <div class="map"><a href="notice.html#directions">오시는길</a></div>
          <i class="fa-solid fa-map-location-dot"></i>
        </div>
      </div>
    </div>
    <div class="preview_widget">
      <div class="today_weather">
        <div class="today_icon"></div>
        <div class="today_temp"></div>
        <div class="today_date"></div>
        <div class="preview_shortcut">
          <p>
            <i class="fa-solid fa-calendar-plus"></i>
          </p>
          <p><i class="fa-solid fa-square-phone-flip"></i></p>
          <p><i class="fa-solid fa-map-location-dot"></i></p>
        </div>
      </div>
    </div>
  </div>

  <div
    class="menu d-flex flex-column justify-content-center align-items-center"
  >
    <ul class="menus d-flex">
      <li>
        <a href="book.html" class="main_menu">예약하기</a>
        <ul>
          <li class="sub_menu disable"><a href="">예약안내</a></li>
          <li class="sub_menu">
            <a href="book.html#book_wrapper">예약하기</a>
          </li>
          <li class="sub_menu disable"><a href="">예약확인</a></li>
        </ul>
      </li>
      <li>
        <a href="course.html" class="main_menu">코스안내</a>
        <ul>
          <li class="sub_menu">
            <a href="course.html#course_wv">코스전경</a>
          </li>
          <li class="sub_menu">
            <a href="course.html#hole_desc">코스소개</a>
          </li>
          <li class="sub_menu">
            <a href="course.html#course_gallery">코스갤러리</a>
          </li>
          <li class="sub_menu">
            <a href="course.html#holeinone">홀인원이벤트</a>
          </li>
        </ul>
      </li>
      <li>
        <a href="" class="main_menu">클럽안내</a>
        <ul>
          <li class="sub_menu"><a href="notice.html#history">연혁/대회</a></li>
          <li class="sub_menu"><a href="notice.html#rocess">이용안내</a></li>
          <li class="sub_menu"><a href="notice.html#facility">시설안내</a></li>
          <li class="sub_menu">
            <a href="notice.html#directions">오시는길</a>
          </li>
        </ul>
      </li>
      <li>
        <a href="board.php" class="main_menu">클럽인포</a>
        <ul>
          <li class="sub_menu">
            <a href="board.php#board_wrapper">공지사항</a>
          </li>
          <li class="sub_menu disable"><a href="">명예의전당</a></li>
        </ul>
      </li>
      <li>
        <a href="login.html" class="main_menu">회원정보</a>
        <ul>
          <li class="sub_menu">
            <a href="session.php">로그인하기</a>
          </li>
          <li class="sub_menu"><a href="session.php">회원정보관리</a></li>
        </ul>
      </li>
    </ul>
    <div class="button">
      <a href="index.html" id="logo-mobile"
        ><img src="./img/logo_white.png" alt=""
      /></a>
    </div>
  </div>
  <div class="icon_mouse">
    <img src="img/icon_mouse.svg" alt="" />
  </div>
</header>