<a href="#" id="go-top"><i class="fa-solid fa-arrow-up"></i></a>
<!-- 탑 버튼 -->

<footer>
  <div class="terms d-flex justify-content-center">
    <a href="">이용약관</a>
    <a href="">웹회원 약관</a>
    <a href="">개인정보처리방침</a>
    <a href="">영상정보처리기기 방침</a>
    <a href="">사업자정보확인</a>
    <a href="">사이트맵</a>
  </div>
  <a href="index.html" class="footer-logo text-center">logo</a>

  <address class="">
    <dl class="d-flex justify-content-center">
      <dt>주소 :</dt>
      <dd>16887 경기도 용인시 처인구 모현읍 능원로 181</dd>
      <dt>대표전화 :</dt>
      <dd>031-334-2111</dd>
      <dt>팩스 :</dt>
      <dd>031-332-2106</dd>
    </dl>
    <dl class="d-flex justify-content-center">
      <dt>팩스 :</dt>
      <dd>031-332-2106</dd>
      <dt>이메일 :</dt>
      <dd>lakeside@lakeside.kr</dd>
    </dl>
    <dl class="d-flex justify-content-center">
      <dt>사업자등록번호</dt>
      <dd>135-81-02491</dd>
      <dt>통신판매신고</dt>
      <dd>제 2009-용인처인-0170호</dd>
      <dt>대표이사</dt>
      <dd>문지태</dd>
    </dl>
    <p class="text-uppercase text-center">
      copyright lakeside country club. all rights reserved
    </p>
  </address>
</footer>
